const INCREASE_SUM = 'INCREASE_SUM';
const DECREASE_SUM = 'DECREASE_SUM';
const RESET_SUM = 'RESET_SUM';
const UPDATE_COUNTER_SIZE = 'UPDATE_COUNTER_SIZE';

export { INCREASE_SUM, DECREASE_SUM, RESET_SUM, UPDATE_COUNTER_SIZE };
